// Auto-generated by services/subscribe-api/scripts/sync-email-i18n.mjs
// Do not edit by hand. Run `npm run subscribe:sync-i18n` from the repo root.

export interface SubscribeEmailStrings {
  confirmSubject: string;
  confirmHeading: string;
  confirmBody: string;
  confirmCta: string;
  confirmFallback: string;
  footerUnsubscribe: string;
}

export const EMAIL_I18N: Record<string, SubscribeEmailStrings> = {
  "ar": {
    "confirmSubject": "أكّد اشتراكك في philoli.com",
    "confirmHeading": "خطوة أخيرة",
    "confirmBody": "اضغط على الزر أدناه لتأكيد اشتراكك. إذا لم تقم بالاشتراك، يمكنك تجاهل هذه الرسالة.",
    "confirmCta": "تأكيد الاشتراك",
    "confirmFallback": "إذا لم يعمل الزر، انسخ هذا الرابط والصقه في متصفحك:",
    "footerUnsubscribe": "إلغاء الاشتراك"
  },
  "bg": {
    "confirmSubject": "Потвърдете абонамента си за philoli.com",
    "confirmHeading": "Още една стъпка",
    "confirmBody": "Кликнете върху бутона по-долу, за да потвърдите абонамента си. Ако не сте се абонирали, можете да игнорирате този имейл.",
    "confirmCta": "Потвърждаване на абонамента",
    "confirmFallback": "Ако бутонът не работи, копирайте и поставете този линк във вашия браузър:",
    "footerUnsubscribe": "Отписване"
  },
  "bn": {
    "confirmSubject": "philoli.com-এ আপনার সাবস্ক্রিপশন নিশ্চিত করুন",
    "confirmHeading": "আর একটি ধাপ",
    "confirmBody": "আপনার সাবস্ক্রিপশন নিশ্চিত করতে নিচের বোতামে ক্লিক করুন। আপনি যদি সাবস্ক্রাইব না করে থাকেন, তবে এই ইমেইলটি উপেক্ষা করতে পারেন।",
    "confirmCta": "সাবস্ক্রিপশন নিশ্চিত করুন",
    "confirmFallback": "যদি বোতামটি কাজ না করে, তবে এই লিঙ্কটি কপি করে আপনার ব্রাউজারে পেস্ট করুন:",
    "footerUnsubscribe": "আনসাবস্ক্রাইব করুন"
  },
  "cs": {
    "confirmSubject": "Potvrďte svůj odběr na philoli.com",
    "confirmHeading": "Ještě jeden krok",
    "confirmBody": "Klikněte na tlačítko níže pro potvrzení odběru. Pokud jste se k odběru nepřihlásili, můžete tento e-mail ignorovat.",
    "confirmCta": "Potvrdit odběr",
    "confirmFallback": "Pokud tlačítko nefunguje, zkopírujte a vložte tento odkaz do svého prohlížeče:",
    "footerUnsubscribe": "Zrušit odběr"
  },
  "da": {
    "confirmSubject": "Bekræft din tilmelding til philoli.com",
    "confirmHeading": "Et skridt mere",
    "confirmBody": "Klik på knappen herunder for at bekræfte din tilmelding. Hvis du ikke har tilmeldt dig, kan du ignorere denne e-mail.",
    "confirmCta": "Bekræft tilmelding",
    "confirmFallback": "Hvis knappen ikke virker, så kopiér og indsæt dette link i din browser:",
    "footerUnsubscribe": "Afmeld"
  },
  "de": {
    "confirmSubject": "Bestätige dein Abonnement für philoli.com",
    "confirmHeading": "Ein Schritt noch",
    "confirmBody": "Klicke auf die Schaltfläche unten, um dein Abonnement zu bestätigen. Falls du dich nicht angemeldet hast, kannst du diese E-Mail ignorieren.",
    "confirmCta": "Abonnement bestätigen",
    "confirmFallback": "Falls die Schaltfläche nicht funktioniert, kopiere diesen Link und füge ihn in deinen Browser ein:",
    "footerUnsubscribe": "Abmelden"
  },
  "el": {
    "confirmSubject": "Επιβεβαιώστε την εγγραφή σας στο philoli.com",
    "confirmHeading": "Ένα ακόμη βήμα",
    "confirmBody": "Κάντε κλικ στο παρακάτω κουμπί για να επιβεβαιώσετε την εγγραφή σας. Αν δεν κάνατε εσείς την εγγραφή, μπορείτε να αγνοήσετε αυτό το email.",
    "confirmCta": "Επιβεβαίωση εγγραφής",
    "confirmFallback": "Αν το κουμπί δεν λειτουργεί, αντιγράψτε και επικολλήστε αυτόν τον σύνδεσμο στο πρόγραμμα περιήγησής σας:",
    "footerUnsubscribe": "Διαγραφή"
  },
  "en": {
    "confirmSubject": "Confirm your subscription to philoli.com",
    "confirmHeading": "One more step",
    "confirmBody": "Click the button below to confirm your subscription. If you didn't subscribe, you can ignore this email.",
    "confirmCta": "Confirm subscription",
    "confirmFallback": "If the button doesn't work, copy and paste this link into your browser:",
    "footerUnsubscribe": "Unsubscribe"
  },
  "es": {
    "confirmSubject": "Confirma tu suscripción a philoli.com",
    "confirmHeading": "Un paso más",
    "confirmBody": "Haz clic en el botón de abajo para confirmar tu suscripción. Si no te has suscrito, puedes ignorar este correo.",
    "confirmCta": "Confirmar suscripción",
    "confirmFallback": "Si el botón no funciona, copia y pega este enlace en tu navegador:",
    "footerUnsubscribe": "Darse de baja"
  },
  "et": {
    "confirmSubject": "Kinnita oma tellimus saidile philoli.com",
    "confirmHeading": "Veel üks samm",
    "confirmBody": "Klõpsa tellimuse kinnitamiseks allolevat nuppu. Kui sa tellimust ei teinud, võid seda e-kirja eirata.",
    "confirmCta": "Kinnita tellimus",
    "confirmFallback": "Kui nupp ei tööta, kopeeri see link ja kleebi see oma brauserisse:",
    "footerUnsubscribe": "Tühista tellimus"
  },
  "fa": {
    "confirmSubject": "عضویت خود در philoli.com را تأیید کنید",
    "confirmHeading": "یک مرحله دیگر",
    "confirmBody": "برای تأیید عضویت خود، روی دکمه زیر کلیک کنید. اگر شما عضو نشده‌اید، می‌توانید این ایمیل را نادیده بگیرید.",
    "confirmCta": "تأیید عضویت",
    "confirmFallback": "اگر دکمه کار نمی‌کند، این لینک را کپی کرده و در مرورگر خود جای‌گذاری کنید:",
    "footerUnsubscribe": "لغو عضویت"
  },
  "fi": {
    "confirmSubject": "Vahvista tilauksesi sivustolle philoli.com",
    "confirmHeading": "Vielä yksi vaihe",
    "confirmBody": "Klikkaa alla olevaa painiketta vahvistaaksesi tilauksesi. Jos et tehnyt tilausta, voit jättää tämän sähköpostin huomiotta.",
    "confirmCta": "Vahvista tilaus",
    "confirmFallback": "Jos painike ei toimi, kopioi ja liitä tämä linkki selaimeesi:",
    "footerUnsubscribe": "Peru tilaus"
  },
  "fil": {
    "confirmSubject": "Kumpirmahin ang iyong subscription sa philoli.com",
    "confirmHeading": "Isa pang hakbang",
    "confirmBody": "I-click ang button sa ibaba para kumpirmahin ang iyong subscription. Kung hindi ka nag-subscribe, maaari mong balewalain ang email na ito.",
    "confirmCta": "Kumpirmahin ang subscription",
    "confirmFallback": "Kung hindi gumagana ang button, kopyahin at i-paste ang link na ito sa iyong browser:",
    "footerUnsubscribe": "Mag-unsubscribe"
  },
  "fr": {
    "confirmSubject": "Confirmez votre abonnement à philoli.com",
    "confirmHeading": "Une dernière étape",
    "confirmBody": "Cliquez sur le bouton ci-dessous pour confirmer votre abonnement. Si vous ne vous êtes pas inscrit, vous pouvez ignorer cet e-mail.",
    "confirmCta": "Confirmer l'abonnement",
    "confirmFallback": "Si le bouton ne fonctionne pas, copiez et collez ce lien dans votre navigateur :",
    "footerUnsubscribe": "Se désabonner"
  },
  "he": {
    "confirmSubject": "אשר את הרישום שלך ל-philoli.com",
    "confirmHeading": "צעד אחד נוסף",
    "confirmBody": "לחץ על הכפתור למטה כדי לאשר את הרישום שלך. אם לא נרשמת, באפשרותך להתעלם מהודעה זו.",
    "confirmCta": "אשר רישום",
    "confirmFallback": "אם הכפתור לא עובד, העתק והדבק את הקישור הזה בדפדפן שלך:",
    "footerUnsubscribe": "בטל רישום"
  },
  "hi": {
    "confirmSubject": "philoli.com के लिए अपनी सदस्यता की पुष्टि करें",
    "confirmHeading": "बस एक और कदम",
    "confirmBody": "अपनी सदस्यता की पुष्टि करने के लिए नीचे दिए गए बटन पर क्लिक करें। यदि आपने सब्सक्राइब नहीं किया है, तो आप इस ईमेल को अनदेखा कर सकते हैं।",
    "confirmCta": "सदस्यता की पुष्टि करें",
    "confirmFallback": "यदि बटन काम नहीं कर रहा है, तो इस लिंक को कॉपी करके अपने ब्राउज़र में पेस्ट करें:",
    "footerUnsubscribe": "अनसब्सक्राइब करें"
  },
  "hr": {
    "confirmSubject": "Potvrdi svoju pretplatu na philoli.com",
    "confirmHeading": "Još jedan korak",
    "confirmBody": "Klikni na gumb ispod kako bi potvrdio/la svoju pretplatu. Ako se nisi pretplatio/la, možeš zanemariti ovu e-poruku.",
    "confirmCta": "Potvrdi pretplatu",
    "confirmFallback": "Ako gumb ne radi, kopirajte i zalijepite ovu poveznicu u svoj preglednik:",
    "footerUnsubscribe": "Odjavi se"
  },
  "hu": {
    "confirmSubject": "Erősítsd meg a feliratkozásodat a philoli.com oldalra",
    "confirmHeading": "Még egy lépés",
    "confirmBody": "Kattints az alábbi gombra a feliratkozás megerősítéséhez. Ha nem te iratkoztál fel, figyelmen kívül hagyhatod ezt az e-mailt.",
    "confirmCta": "Feliratkozás megerősítése",
    "confirmFallback": "Ha a gomb nem működik, másold ki és illeszd be ezt a linket a böngésződbe:",
    "footerUnsubscribe": "Leiratkozás"
  },
  "id": {
    "confirmSubject": "Konfirmasi langganan Anda ke philoli.com",
    "confirmHeading": "Satu langkah lagi",
    "confirmBody": "Klik tombol di bawah untuk mengonfirmasi langganan Anda. Jika Anda tidak merasa berlangganan, Anda bisa mengabaikan email ini.",
    "confirmCta": "Konfirmasi langganan",
    "confirmFallback": "Jika tombol tidak berfungsi, salin dan tempel tautan ini ke browser Anda:",
    "footerUnsubscribe": "Berhenti berlangganan"
  },
  "it": {
    "confirmSubject": "Conferma la tua iscrizione a philoli.com",
    "confirmHeading": "Un ultimo passaggio",
    "confirmBody": "Clicca sul pulsante qui sotto per confermare la tua iscrizione. Se non ti sei iscritto, puoi ignorare questa email.",
    "confirmCta": "Conferma iscrizione",
    "confirmFallback": "Se il pulsante non funziona, copia e incolla questo link nel tuo browser:",
    "footerUnsubscribe": "Disiscriviti"
  },
  "ja": {
    "confirmSubject": "philoli.comの購読確認",
    "confirmHeading": "あと一歩です",
    "confirmBody": "下のボタンをクリックして購読を確定してください。もし心当たりがない場合は、このメールを無視してください。",
    "confirmCta": "購読を確定する",
    "confirmFallback": "ボタンが機能しない場合は、このリンクをコピーしてブラウザに貼り付けてください：",
    "footerUnsubscribe": "登録解除"
  },
  "ko": {
    "confirmSubject": "philoli.com 구독을 확인해 주세요",
    "confirmHeading": "마지막 단계",
    "confirmBody": "아래 버튼을 클릭하여 구독을 확인해 주세요. 본인이 구독하지 않았다면 이 이메일을 무시하셔도 됩니다.",
    "confirmCta": "구독 확인",
    "confirmFallback": "버튼이 작동하지 않으면, 이 링크를 복사하여 브라우저에 붙여넣으세요:",
    "footerUnsubscribe": "구독 취소"
  },
  "lt": {
    "confirmSubject": "Patvirtinkite savo prenumeratą philoli.com",
    "confirmHeading": "Dar vienas žingsnis",
    "confirmBody": "Spustelėkite žemiau esantį mygtuką, kad patvirtintumėte prenumeratą. Jei neužsiprenumeravote, galite ignoruoti šį el. laišką.",
    "confirmCta": "Patvirtinti prenumeratą",
    "confirmFallback": "Jei mygtukas neveikia, nukopijuokite ir įklijuokite šią nuorodą į savo naršyklę:",
    "footerUnsubscribe": "Atsisakyti prenumeratos"
  },
  "lv": {
    "confirmSubject": "Apstipriniet savu abonementu vietnē philoli.com",
    "confirmHeading": "Vēl viens solis",
    "confirmBody": "Noklikšķiniet uz zemāk esošās pogas, lai apstiprinātu savu abonementu. Ja jūs neabonējāt, varat ignorēt šo e-pastu.",
    "confirmCta": "Apstiprināt abonementu",
    "confirmFallback": "Ja poga nedarbojas, nokopējiet un ielīmējiet šo saiti savā pārlūkprogrammā:",
    "footerUnsubscribe": "Atteikties no abonēšanas"
  },
  "ms": {
    "confirmSubject": "Sahkan langganan anda ke philoli.com",
    "confirmHeading": "Satu langkah lagi",
    "confirmBody": "Klik butang di bawah untuk mengesahkan langganan anda. Jika anda tidak melanggan, anda boleh abaikan e-mel ini.",
    "confirmCta": "Sahkan langganan",
    "confirmFallback": "Jika butang tidak berfungsi, salin dan tampal pautan ini ke dalam pelayar anda:",
    "footerUnsubscribe": "Nyahlanggan"
  },
  "nl": {
    "confirmSubject": "Bevestig je abonnement op philoli.com",
    "confirmHeading": "Nog één stap",
    "confirmBody": "Klik op de onderstaande knop om je abonnement te bevestigen. Als je je niet hebt aangemeld, kun je deze e-mail negeren.",
    "confirmCta": "Abonnement bevestigen",
    "confirmFallback": "Als de knop niet werkt, kopieer en plak deze link dan in je browser:",
    "footerUnsubscribe": "Uitschrijven"
  },
  "no": {
    "confirmSubject": "Bekreft abonnementet ditt på philoli.com",
    "confirmHeading": "Ett steg til",
    "confirmBody": "Klikk på knappen nedenfor for å bekrefte abonnementet ditt. Hvis du ikke har meldt deg på, kan du ignorere denne e-posten.",
    "confirmCta": "Bekreft abonnement",
    "confirmFallback": "Hvis knappen ikke fungerer, kopier og lim inn denne lenken i nettleseren din:",
    "footerUnsubscribe": "Avmeld"
  },
  "pl": {
    "confirmSubject": "Potwierdź swoją subskrypcję philoli.com",
    "confirmHeading": "Jeszcze jeden krok",
    "confirmBody": "Kliknij poniższy przycisk, aby potwierdzić subskrypcję. Jeśli nie dokonywałeś subskrypcji, możesz zignorować tę wiadomość.",
    "confirmCta": "Potwierdź subskrypcję",
    "confirmFallback": "Jeśli przycisk nie działa, skopiuj i wklej ten link do swojej przeglądarki:",
    "footerUnsubscribe": "Anuluj subskrypcję"
  },
  "pt": {
    "confirmSubject": "Confirme sua inscrição em philoli.com",
    "confirmHeading": "Mais um passo",
    "confirmBody": "Clique no botão abaixo para confirmar sua inscrição. Se você não se inscreveu, pode ignorar este e-mail.",
    "confirmCta": "Confirmar inscrição",
    "confirmFallback": "Se o botão não funcionar, copie e cole este link no seu navegador:",
    "footerUnsubscribe": "Cancelar inscrição"
  },
  "ro": {
    "confirmSubject": "Confirmă-ți abonarea la philoli.com",
    "confirmHeading": "Încă un pas",
    "confirmBody": "Apasă butonul de mai jos pentru a confirma abonarea. Dacă nu te-ai abonat, poți ignora acest e-mail.",
    "confirmCta": "Confirmă abonarea",
    "confirmFallback": "Dacă butonul nu funcționează, copiază și lipește acest link în browserul tău:",
    "footerUnsubscribe": "Dezabonează-te"
  },
  "ru": {
    "confirmSubject": "Подтвердите подписку на philoli.com",
    "confirmHeading": "Еще один шаг",
    "confirmBody": "Нажмите кнопку ниже, чтобы подтвердить подписку. Если вы не подписывались, можете проигнорировать это письмо.",
    "confirmCta": "Подтвердить подписку",
    "confirmFallback": "Если кнопка не работает, скопируйте и вставьте эту ссылку в ваш браузер:",
    "footerUnsubscribe": "Отписаться"
  },
  "sk": {
    "confirmSubject": "Potvrďte svoj odber na philoli.com",
    "confirmHeading": "Ešte jeden krok",
    "confirmBody": "Kliknite na tlačidlo nižšie a potvrďte svoj odber. Ak ste sa neprihlásili, tento e-mail môžete ignorovať.",
    "confirmCta": "Potvrdiť odber",
    "confirmFallback": "Ak tlačidlo nefunguje, skopírujte a vložte tento odkaz do svojho prehliadača:",
    "footerUnsubscribe": "Zrušiť odber"
  },
  "sl": {
    "confirmSubject": "Potrdite svojo naročnino na philoli.com",
    "confirmHeading": "Še en korak",
    "confirmBody": "Kliknite spodnji gumb za potrditev naročnine. Če se niste naročili, lahko to e-poštno sporočilo prezrete.",
    "confirmCta": "Potrdi naročnino",
    "confirmFallback": "Če gumb ne deluje, kopirajte in prilepite to povezavo v svoj brskalnik:",
    "footerUnsubscribe": "Odjavi se"
  },
  "sr": {
    "confirmSubject": "Potvrdi svoju pretplatu na philoli.com",
    "confirmHeading": "Još jedan korak",
    "confirmBody": "Klikni na dugme ispod da potvrdiš svoju pretplatu. Ako se nisi prijavio/la, možeš ignorisati ovu poruku.",
    "confirmCta": "Potvrdi pretplatu",
    "confirmFallback": "Ako dugme ne radi, kopirajte i nalepite ovaj link u svoj pretraživač:",
    "footerUnsubscribe": "Odjavi se"
  },
  "sv": {
    "confirmSubject": "Bekräfta din prenumeration på philoli.com",
    "confirmHeading": "Ett steg till",
    "confirmBody": "Klicka på knappen nedan för att bekräfta din prenumeration. Om du inte har prenumererat kan du ignorera detta mejl.",
    "confirmCta": "Bekräfta prenumeration",
    "confirmFallback": "Om knappen inte fungerar, kopiera och klistra in den här länken i din webbläsare:",
    "footerUnsubscribe": "Avsluta prenumeration"
  },
  "th": {
    "confirmSubject": "ยืนยันการติดตาม philoli.com ของคุณ",
    "confirmHeading": "อีกขั้นตอนเดียว",
    "confirmBody": "คลิกปุ่มด้านล่างเพื่อยืนยันการติดตามของคุณ หากคุณไม่ได้เป็นผู้สมัครรับข้อมูล คุณสามารถเพิกเฉยต่ออีเมลฉบับนี้ได้",
    "confirmCta": "ยืนยันการติดตาม",
    "confirmFallback": "หากปุ่มไม่ทำงาน ให้คัดลอกและวางลิงก์นี้ลงในเบราว์เซอร์ของคุณ:",
    "footerUnsubscribe": "ยกเลิกการติดตาม"
  },
  "tr": {
    "confirmSubject": "philoli.com aboneliğinizi onaylayın",
    "confirmHeading": "Bir adım daha",
    "confirmBody": "Aboneliğinizi onaylamak için aşağıdaki düğmeye tıklayın. Eğer abone olmadıysanız, bu e-postayı görmezden gelebilirsiniz.",
    "confirmCta": "Aboneliği onayla",
    "confirmFallback": "Eğer buton çalışmıyorsa, bu bağlantıyı kopyalayıp tarayıcınıza yapıştırın:",
    "footerUnsubscribe": "Abonelikten çık"
  },
  "uk": {
    "confirmSubject": "Підтвердьте свою підписку на philoli.com",
    "confirmHeading": "Ще один крок",
    "confirmBody": "Натисніть кнопку нижче, щоб підтвердити підписку. Якщо ви не підписувалися, можете проігнорувати цей лист.",
    "confirmCta": "Підтвердити підписку",
    "confirmFallback": "Якщо кнопка не працює, скопіюйте та вставте це посилання у свій браузер:",
    "footerUnsubscribe": "Відписатися"
  },
  "vi": {
    "confirmSubject": "Xác nhận đăng ký của bạn với philoli.com",
    "confirmHeading": "Thêm một bước nữa",
    "confirmBody": "Nhấp vào nút bên dưới để xác nhận đăng ký của bạn. Nếu bạn không thực hiện đăng ký, bạn có thể bỏ qua email này.",
    "confirmCta": "Xác nhận đăng ký",
    "confirmFallback": "Nếu nút không hoạt động, hãy sao chép và dán liên kết này vào trình duyệt của bạn:",
    "footerUnsubscribe": "Hủy đăng ký"
  },
  "zh": {
    "confirmSubject": "确认您对 philoli.com 的订阅",
    "confirmHeading": "只差最后一步",
    "confirmBody": "点击下方按钮确认您的订阅。如果您并未订阅，可以忽略此邮件。",
    "confirmCta": "确认订阅",
    "confirmFallback": "如果按钮无法使用，请将此链接复制并粘贴到您的浏览器中：",
    "footerUnsubscribe": "取消订阅"
  },
  "zh-TW": {
    "confirmSubject": "確認您對 philoli.com 的訂閱",
    "confirmHeading": "最後一步",
    "confirmBody": "點擊下方按鈕以確認您的訂閱。如果您並未訂閱，可以忽略此郵件。",
    "confirmCta": "確認訂閱",
    "confirmFallback": "如果按鈕無法運作，請將此連結複製並貼上到您的瀏覽器中：",
    "footerUnsubscribe": "取消訂閱"
  }
};
